### ISSUE TITLE
Full screen events not working in Android

### ISSUE THREAD

**Issue by SystemBlad** [NZME/react-native-brightcove-ima-player#1]
Hi, I was testing this great library, I just had noticed  that these  events are not being fired in Android:

1. onEnterFullscreen
2. onExitFullscreen

**Comment by matejdr** [comment]
That was fixed in this commit: https://github.com/NZME/react-native-brightcove-ima-player/commit/cdf81d2cdff92360ff980fd05f24edb5d6a53f55

Feel free to download the latest version, 2.20 at the moment, and re-test.
Thank you.

**Comment by aleccolville-nzme** [comment]
closing
