### ISSUE TITLE
what is - IMAUrl

### ISSUE THREAD

**Issue by osliver** [NZME/react-native-brightcove-ima-player#3]
Player need settings with IMAUrl value, what is it?

**Comment by aleccolville-nzme** [comment]
it's a template from your ad provider - eg 'https://pubads.g.doubleclick.net/gampad/ads?iu=/111111111/jeff&description_url=http%3A%2F%2Fyourdomain.com&env=vp&impl=s&correlator=&tfcd=0&npa=0&gdfp_req=1&output=vast&sz=620x350&unviewed_position_start=1'

**Comment by aleccolville-nzme** [comment]
closing
